services:
    route:
        class: Opine\Route\Service
        arguments:
            - %root%
            - "@container"
    routeModel:
        class: Opine\Route\Model
        arguments:
            - %root%
            - "@route"
            - "@bundleModel"
    redirect:
        class: Opine\Route\Redirect
        scope: prototype
        arguments:
            - "@route"
