imports:
    - package-container.yml
    - ../vendor/opine/bundle/config/containers/package-container.yml

services:
    controller:
        class: Controller
        arguments:
            - @redirect